services:
  - type: web
    name: task_management-webapp
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn task_management.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: task_management.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
